server:
  port: 9297

spring:
  application:
    name: cgms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mtembi/cgms-config-server.git
          clone-on-start: true